	Vagrant.configure(2) do |config|

		config.vm.define "puppetcontrol" do |ctl|
			ctl.vm.box = "ubuntu/trusty64"
			ctl.vm.hostname = "puppetMaster"
			ctl.vm.network "private_network", ip: "192.168.25.2"
			ctl.vm.provider "virtualbox" do |vb|
				vb.memory = 1024
			end
					
		end


		config.vm.define "puppetnode1" do |n1|
			n1.vm.box = "ubuntu/trusty64"
			n1.vm.hostname = "puppetnode1"
			n1.vm.network "private_network", ip: "192.168.25.3"
			n1.vm.provider "virtualbox" do |vb|
				vb.memory = 1024
			end
		end
		
		
	end