	Vagrant.configure(2) do |config|

		config.vm.define "control" do |ctl|
			ctl.vm.box = "ubuntu/trusty64"
			ctl.vm.hostname = "Master"
			ctl.vm.network "private_network", ip: "192.168.15.2"
			ctl.vm.provider "virtualbox" do |vb|
				vb.memory = 1024
			end
			config.vm.provision :shell, path: "bootstrap.sh"
			
		end


		config.vm.define "node1" do |n1|
			n1.vm.box = "ubuntu/trusty64"
			n1.vm.hostname = "webnode1"
			n1.vm.network "private_network", ip: "192.168.15.3"
			n1.vm.provider "virtualbox" do |vb|
				vb.memory = 1024
			end
		end


		config.vm.define "node2" do |n2|
			n2.vm.box = "ubuntu/trusty64"
			n2.vm.hostname = "webnode2"
			n2.vm.network "private_network", ip: "192.168.15.4"
			n2.vm.provider "virtualbox" do |vb|
				vb.memory = 1024
			end
		end
		
		
	end